apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
      - image: openspeedtest/latest
        name: speedtest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: speedtest
  name: speedtest
spec:
  ports:
    - port: 3000
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 3000
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007

  selector:
    app: speedtest
  sessionAffinity: None
  type: NodePort


#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: speedtest
#spec:
#  ingressClassName: nginx
#  rules:
#  - host: sss.devopscicd.cc
#    http:
#      paths:
#      - path: /
#        pathType: ImplementationSpecific
#        backend:
#          service:
#            name: speedtest
#            port:
#              number: 3000#
